---

- name: Read gitea init file
  kubernetes.core.k8s_exec:
    namespace: "{{gitea_k8s_container_app_namespace}}"
    pod: "{{gitea_k8s_container_app_pod}}"
    command: "/bin/bash -c 'cat {{ gitea_config_path }}'"
  register: gitea_ini

- name: Get params
  ansible.builtin.set_fact:
    data_path: "{{ gitea_ini.stdout | frantchenco.gitea.parse_ini(section='a', name='a', default=gitea_default_data_path) }}"
    repo_path: "{{ gitea_ini.stdout | frantchenco.gitea.parse_ini(section='repository', name='ROOT', default=gitea_default_repo_path) }}"
    custom_tmp_local_copy_path: "{{ gitea_ini.stdout | frantchenco.gitea.parse_ini(section='repository.local', name='LOCAL_COPY_PATH', default=gitea_default_custom_tmp_local_copy_path) }}"
    custom_indexer_path: "{{ gitea_ini.stdout | frantchenco.gitea.parse_ini(section='indexer', name='ISSUE_INDEXER_PATH', default=gitea_default_custom_indexer_path) }}"
    custom_avatar_path: "{{ gitea_ini.stdout | frantchenco.gitea.parse_ini(section='picture', name='AVATAR_UPLOAD_PATH', default=gitea_default_custom_avatar_path) }}"
    db_type: "{{ gitea_ini.stdout | frantchenco.gitea.parse_ini(section='database', name='DB_TYPE', default='bla') }}"
    db_host: "{{ gitea_ini.stdout | frantchenco.gitea.parse_ini(section='database', name='HOST', default='bla') }}"
    db_database: "{{ gitea_ini.stdout | frantchenco.gitea.parse_ini(section='database', name='NAME', default='bla') }}"
    db_username: "{{ gitea_ini.stdout | frantchenco.gitea.parse_ini(section='database', name='USER', default='bla') }}"
    db_password: "{{ gitea_ini.stdout | frantchenco.gitea.parse_ini(section='database', name='PASSWD', default='bla') }}"
    db_ssl_mode: "{{ gitea_ini.stdout | frantchenco.gitea.parse_ini(section='database', name='SSL_MODE', default='bla') }}"
    db_charset: "{{ gitea_ini.stdout | frantchenco.gitea.parse_ini(section='database', name='CHARSET', default='bla') }}"
    db_path: "{{ gitea_ini.stdout | frantchenco.gitea.parse_ini(section='database', name='PATH', default='bla') }}"

- name: backup data
  shell: "{{gitea_k8s_app}} cp {{temp_folder_path}}/data {{gitea_k8s_container_app_pod}}:{{data_path}} -n {{gitea_k8s_container_app_namespace}}"

- name: backup repo
  shell: "{{gitea_k8s_app}} cp {{temp_folder_path}}/repo {{gitea_k8s_container_app_pod}}:{{repo_path}} -n {{gitea_k8s_container_app_namespace}}"

- name: backup tmp
  shell: "{{gitea_k8s_app}} cp {{temp_folder_path}}/tmp {{gitea_k8s_container_app_pod}}:{{custom_tmp_local_copy_path}} -n {{gitea_k8s_container_app_namespace}}"
  ignore_errors: true

- name: backup avatars
  shell: "{{gitea_k8s_app}} cp {{temp_folder_path}}/avatars {{gitea_k8s_container_app_pod}}:{{custom_avatar_path}} -n {{gitea_k8s_container_app_namespace}}"
  ignore_errors: true

- name: backup indexer
  shell: "{{gitea_k8s_app}} cp {{temp_folder_path}}/indexer {{gitea_k8s_container_app_pod}}:{{custom_indexer_path}} -n {{gitea_k8s_container_app_namespace}}"
  ignore_errors: true

- name: MSQL database - copy dump
  shell: "{{gitea_k8s_app}} cp {{temp_folder_path}}/dump.sql {{gitea_k8s_container_db_pod}}:/tmp/dump.sql -n {{gitea_k8s_container_app_namespace}}"

- name: MSQL database - restore
  kubernetes.core.k8s_exec:
    namespace: "{{gitea_k8s_container_db_namespace}}"
    pod: "{{gitea_k8s_container_db_pod}}"
    command: "/bin/bash -c 'mysql --user={{db_username}} --password={{db_password}} {{db_database}} < /tmp/dump.sql'"

- name: MSQL database - delete dump
  kubernetes.core.k8s_exec:
    namespace: "{{gitea_k8s_container_db_namespace}}"
    pod: "{{gitea_k8s_container_db_pod}}"
    command: "/bin/bash -c 'rm /tmp/dump.sql'"
