---
gitea_installation: local # docker, kubernetes
gitea_backup_prefix: gitea-backup
gitea_retention_count: 3
gitea_backup_methode: s3

gitea_config_path: /data/gitea/conf/app.ini
gitea_default_repo_path: /data/git/repositories
gitea_default_avatar_path: /data/avatars
gitea_default_avatar_repo_path: /data/repo-avatars
